//! Settings resolution layer: DB → compiled defaults.

use anyhow::{Context, Result};

use crate::config::Config;
use crate::db::Database;

/// Where a setting's effective value came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SettingSource {
    Default,
    Database,
}

impl std::fmt::Display for SettingSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SettingSource::Default => write!(f, "default"),
            SettingSource::Database => write!(f, "db"),
        }
    }
}

/// One entry in the full settings listing.
#[derive(Debug, Clone)]
pub struct SettingInfo {
    pub key: String,
    pub value: String,
    pub source: SettingSource,
}

pub type SettingExtractor = fn(&Config) -> String;

// SETTING_REGISTRY is generated by the define_settings! macro in config/settings_table.rs
pub use crate::config::settings_table::{SETTING_REGISTRY, TUI_SETTINGS};

/// How a TUI settings popup should render and edit a setting.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TuiSettingKind {
    /// Boolean toggle (Space toggles).
    Bool,
    /// Float with arrow-step (±0.1).
    Float,
    /// Unsigned integer (Enter opens edit buffer).
    Uint,
    /// Select from an enum/provider list (Left/Right cycles).
    Select,
}

/// Display metadata for a TUI-visible setting. Emitted by the `tui_settings`
/// block of `define_settings!` so the popup list lives alongside the registry
/// rather than in a separate source of truth.
#[derive(Debug, Clone, Copy)]
pub struct TuiSettingDecl {
    /// Key in `SETTING_REGISTRY`. Must resolve at runtime.
    pub key: &'static str,
    /// Human-facing label shown in the popup row.
    pub label: &'static str,
    /// Control type for input handling.
    pub kind: TuiSettingKind,
    /// Section header under which this entry renders.
    pub category: &'static str,
}

/// All known setting keys, derived from `SETTING_REGISTRY`.
pub static ALL_SETTING_KEYS: std::sync::LazyLock<Vec<&'static str>> =
    std::sync::LazyLock::new(|| SETTING_REGISTRY.iter().map(|(k, _)| *k).collect());

/// Merges settings from two layers: DB overrides → compiled defaults.
pub struct SettingsResolver {
    db: Database,
}

impl SettingsResolver {
    /// Open the database for settings resolution.
    pub fn load() -> Result<Self> {
        let db = Database::open().with_context(|| "Failed to open database for settings")?;
        Ok(Self { db })
    }

    /// Build from a pre-existing Database.
    pub fn new(db: Database) -> Self {
        Self { db }
    }

    /// Resolve a full Config from defaults + DB overrides.
    pub fn resolve(&self) -> Result<Config> {
        let mut config = Config::default();
        let db_settings = self.db.list_settings()?;
        for (key, value, _) in &db_settings {
            if let Err(e) = config.apply_setting(key, value) {
                tracing::warn!("Ignoring invalid setting {key}: {e}");
            }
        }
        Ok(config)
    }

    /// Validate and write a setting to the database.
    /// Returns the confirmation string from `apply_setting`.
    pub fn set(&self, key: &str, value: &str) -> Result<String> {
        // Validate by applying to a throwaway config
        let mut scratch = Config::default();
        let confirmation = scratch.apply_setting(key, value)?;
        self.db.set_setting(key, value)?;
        Ok(confirmation)
    }

    /// Revert a setting to its compiled default value.
    /// Writes the default back to the DB rather than deleting the row,
    /// keeping the settings table as the complete source of truth.
    pub fn unset(&self, key: &str) -> Result<()> {
        let defaults = Config::default();
        let default_value = config_value_for_key(&defaults, key)
            .ok_or_else(|| anyhow::anyhow!("Unknown setting key: {key}"))?;
        self.db.set_setting(key, &default_value)?;
        Ok(())
    }

    /// Get the effective value and its source for a single key.
    /// Source is determined by comparing the DB value to the compiled default:
    /// matching values report `Default`, differing values report `Database`.
    pub fn get_with_source(&self, key: &str) -> Result<(String, SettingSource)> {
        let defaults = Config::default();
        let default_value = config_value_for_key(&defaults, key)
            .ok_or_else(|| anyhow::anyhow!("Unknown setting key: {key}"))?;

        if let Some(db_value) = self.db.get_setting(key)? {
            let source = if db_value == default_value {
                SettingSource::Default
            } else {
                SettingSource::Database
            };
            return Ok((db_value, source));
        }

        // Fallback for keys not yet seeded (e.g. new setting added between startups)
        Ok((default_value, SettingSource::Default))
    }

    /// List all settings with their effective values and sources.
    pub fn list_all(&self) -> Result<Vec<SettingInfo>> {
        let mut result = Vec::new();
        for &key in ALL_SETTING_KEYS.iter() {
            match self.get_with_source(key) {
                Ok((value, source)) => result.push(SettingInfo {
                    key: key.to_string(),
                    value,
                    source,
                }),
                Err(e) => {
                    tracing::warn!("Failed to resolve setting {key}: {e}");
                    continue;
                }
            }
        }
        Ok(result)
    }

    /// Access the underlying database.
    pub fn database(&self) -> &Database {
        &self.db
    }
}

/// Extract the current string value of a config key.
pub fn config_value_for_key(config: &Config, key: &str) -> Option<String> {
    SETTING_REGISTRY
        .iter()
        .find(|(k, _)| *k == key)
        .map(|(_, extract)| extract(config))
}

#[cfg(test)]
mod tests {
    use super::*;
    use rusqlite::Connection;

    fn test_resolver() -> SettingsResolver {
        let conn = Connection::open_in_memory().expect("open in-memory db");
        let db = Database::from_connection(conn).expect("db setup");
        SettingsResolver::new(db)
    }

    #[test]
    fn defaults_resolve_without_db() {
        let resolver = test_resolver();
        let config = resolver.resolve().unwrap();
        assert!((config.llm.temperature - 0.7).abs() < f32::EPSILON);
    }

    #[test]
    fn db_overrides_default() {
        let resolver = test_resolver();
        resolver.set("temperature", "1.2").unwrap();
        let config = resolver.resolve().unwrap();
        assert!((config.llm.temperature - 1.2).abs() < f32::EPSILON);
    }

    #[test]
    fn unset_reverts_to_default() {
        let resolver = test_resolver();
        resolver.set("temperature", "1.2").unwrap();
        resolver.unset("temperature").unwrap();
        let config = resolver.resolve().unwrap();
        assert!((config.llm.temperature - 0.7).abs() < f32::EPSILON);
    }

    #[test]
    fn get_with_source_default() {
        let resolver = test_resolver();
        let (val, source) = resolver.get_with_source("temperature").unwrap();
        assert_eq!(val, "0.7");
        assert_eq!(source, SettingSource::Default);
    }

    #[test]
    fn get_with_source_db() {
        let resolver = test_resolver();
        resolver.set("temperature", "0.9").unwrap();
        let (val, source) = resolver.get_with_source("temperature").unwrap();
        assert_eq!(val, "0.9");
        assert_eq!(source, SettingSource::Database);
    }

    #[test]
    fn evolution_enabled_round_trip() {
        let resolver = test_resolver();
        let (val, source) = resolver.get_with_source("evolution.enabled").unwrap();
        assert_eq!(val, "true");
        assert_eq!(source, SettingSource::Default);

        resolver.set("evolution.enabled", "false").unwrap();
        let (val, source) = resolver.get_with_source("evolution.enabled").unwrap();
        assert_eq!(val, "false");
        assert_eq!(source, SettingSource::Database);
    }

    #[test]
    fn evolution_enabled_in_list_all() {
        let resolver = test_resolver();
        let all = resolver.list_all().unwrap();
        assert!(all.iter().any(|s| s.key == "evolution.enabled"));
    }

    #[test]
    fn invalid_key_errors() {
        let resolver = test_resolver();
        assert!(resolver.set("nonexistent", "value").is_err());
    }

    #[test]
    fn invalid_value_errors() {
        let resolver = test_resolver();
        assert!(resolver.set("temperature", "5.0").is_err());
    }

    #[test]
    fn every_tui_setting_is_registered() {
        // Guard: the `tui_settings` block must only reference keys that are
        // also defined in `registry_and_apply` / `custom_apply` (otherwise
        // the popup will silently show blank values).
        let known: std::collections::HashSet<&str> =
            SETTING_REGISTRY.iter().map(|(k, _)| *k).collect();
        for decl in TUI_SETTINGS {
            assert!(
                known.contains(decl.key),
                "TUI setting '{}' is not in SETTING_REGISTRY",
                decl.key
            );
        }
    }

    #[test]
    fn list_all_returns_all_keys() {
        let resolver = test_resolver();
        let all = resolver.list_all().unwrap();
        assert!(all.len() >= 14); // at least the original 14 settings
        assert!(all.iter().any(|s| s.key == "temperature"));
        assert!(all
            .iter()
            .any(|s| s.key == "conversation.tool_output_max_tokens"));
    }

    #[test]
    fn json_secret_ref_round_trip() {
        let resolver = test_resolver();
        let json =
            r#"{"source":"exec","command":"security","args":["find-generic-password","-w"]}"#;
        resolver.set("llm.api_key", json).unwrap();
        let config = resolver.resolve().unwrap();
        assert!(config.llm.api_key.is_some());
        let (val, source) = resolver.get_with_source("llm.api_key").unwrap();
        assert_eq!(source, SettingSource::Database);
        assert!(val.contains("exec"));
    }

    #[test]
    fn json_gateway_bindings_round_trip() {
        let resolver = test_resolver();
        let json = r#"[{"channel":"telegram","provider":"anthropic","model":"claude-sonnet-4"}]"#;
        resolver.set("gateway.bindings", json).unwrap();
        let config = resolver.resolve().unwrap();
        assert_eq!(config.gateway.bindings.len(), 1);
        assert_eq!(config.gateway.bindings[0].channel, "telegram");
    }

    #[test]
    fn json_credentials_round_trip() {
        let resolver = test_resolver();
        let json = r#"{"SLACK_TOKEN":"SLACK_TOKEN"}"#;
        resolver.set("credentials", json).unwrap();
        let config = resolver.resolve().unwrap();
        assert!(config.credentials.contains_key("SLACK_TOKEN"));
    }

    #[test]
    fn user_name_round_trip() {
        let resolver = test_resolver();
        resolver.set("user.name", "mike").unwrap();
        let config = resolver.resolve().unwrap();
        assert_eq!(config.user.name.as_deref(), Some("mike"));
    }

    #[test]
    fn llm_thinking_round_trip() {
        let resolver = test_resolver();
        resolver.set("llm.thinking", "high").unwrap();
        let config = resolver.resolve().unwrap();
        assert!(config.llm.thinking.is_enabled());
    }

    #[test]
    fn tools_policy_allow_round_trip() {
        let resolver = test_resolver();
        let json = r#"["group:git","browser"]"#;
        resolver.set("tools.policy.allow", json).unwrap();
        let config = resolver.resolve().unwrap();
        assert_eq!(config.tools.policy.allow, vec!["group:git", "browser"]);
    }

    #[test]
    fn heartbeat_channels_round_trip() {
        let resolver = test_resolver();
        resolver
            .set("heartbeat.channels", r#"["telegram","slack"]"#)
            .unwrap();
        let config = resolver.resolve().unwrap();
        assert_eq!(config.heartbeat.channels, vec!["telegram", "slack"]);
    }

    #[test]
    fn security_blocked_paths_round_trip() {
        let resolver = test_resolver();
        resolver
            .set("security.blocked_paths", r#"[".ssh",".env"]"#)
            .unwrap();
        let config = resolver.resolve().unwrap();
        assert_eq!(config.security.blocked_paths, vec![".ssh", ".env"]);
    }

    #[test]
    fn invalid_json_setting_errors() {
        let resolver = test_resolver();
        assert!(resolver.set("gateway.bindings", "not json").is_err());
        assert!(resolver.set("llm.api_key", "{bad}").is_err());
    }

    #[test]
    fn new_scalar_settings_round_trip() {
        let resolver = test_resolver();

        resolver.set("llm.max_retries", "5").unwrap();
        resolver.set("gateway.port", "8080").unwrap();
        resolver.set("agents.enabled", "false").unwrap();
        resolver.set("debug.llm_logging", "true").unwrap();
        resolver.set("web.enabled", "false").unwrap();

        let config = resolver.resolve().unwrap();
        assert_eq!(config.llm.max_retries, 5);
        assert_eq!(config.gateway.port, 8080);
        assert!(!config.agents.enabled);
        assert!(config.debug.llm_logging);
        assert!(!config.web.enabled);
    }

    // ── DB-as-source-of-truth tests ──

    #[test]
    fn ensure_all_settings_seeds_defaults() {
        let resolver = test_resolver();
        let settings = resolver.database().list_settings().unwrap();
        // After from_connection (which calls ensure_all_settings via init_connection),
        // every SETTING_REGISTRY key should have a row.
        assert_eq!(
            settings.len(),
            SETTING_REGISTRY.len(),
            "expected {} settings rows, got {}",
            SETTING_REGISTRY.len(),
            settings.len()
        );
        let keys: Vec<&str> = settings.iter().map(|(k, _, _)| k.as_str()).collect();
        for &(key, _) in SETTING_REGISTRY.iter() {
            assert!(keys.contains(&key), "missing setting key: {key}");
        }
    }

    #[test]
    fn ensure_all_settings_preserves_overrides() {
        let resolver = test_resolver();
        resolver.set("temperature", "1.5").unwrap();
        // Re-seed — should not clobber the override
        resolver.database().ensure_all_settings().unwrap();
        let (val, source) = resolver.get_with_source("temperature").unwrap();
        assert_eq!(val, "1.5");
        assert_eq!(source, SettingSource::Database);
    }

    #[test]
    fn ensure_all_settings_idempotent() {
        let resolver = test_resolver();
        let before = resolver.database().list_settings().unwrap();
        resolver.database().ensure_all_settings().unwrap();
        let after = resolver.database().list_settings().unwrap();
        assert_eq!(before.len(), after.len());
        for ((k1, v1, _), (k2, v2, _)) in before.iter().zip(after.iter()) {
            assert_eq!(k1, k2);
            assert_eq!(v1, v2, "value changed for key {k1}");
        }
    }

    #[test]
    fn unset_writes_default_not_delete() {
        let resolver = test_resolver();
        resolver.set("temperature", "1.5").unwrap();
        resolver.unset("temperature").unwrap();
        // Row should still exist in DB with the default value
        let db_val = resolver.database().get_setting("temperature").unwrap();
        assert_eq!(db_val, Some("0.7".to_string()));
        // Source should report Default since value matches compiled default
        let (val, source) = resolver.get_with_source("temperature").unwrap();
        assert_eq!(val, "0.7");
        assert_eq!(source, SettingSource::Default);
    }

    #[test]
    fn get_source_default_for_seeded() {
        let resolver = test_resolver();
        // All settings are seeded with defaults — should report Default source
        let (_, source) = resolver.get_with_source("sandbox.enabled").unwrap();
        assert_eq!(source, SettingSource::Default);
    }

    #[test]
    fn get_source_database_for_modified() {
        let resolver = test_resolver();
        resolver.set("sandbox.enabled", "false").unwrap();
        let (val, source) = resolver.get_with_source("sandbox.enabled").unwrap();
        assert_eq!(val, "false");
        assert_eq!(source, SettingSource::Database);
    }

    #[test]
    fn list_all_complete_after_seeding() {
        let resolver = test_resolver();
        let all = resolver.list_all().unwrap();
        assert_eq!(
            all.len(),
            SETTING_REGISTRY.len(),
            "list_all should return exactly SETTING_REGISTRY.len() entries"
        );
    }

    #[test]
    fn data_version_available() {
        let resolver = test_resolver();
        let v1 = resolver.database().data_version().unwrap();
        assert!(v1 >= 0, "data_version should be non-negative");
    }

    // ── Macro-generated setter kind coverage ──

    #[test]
    fn setter_string_kind() {
        let mut config = Config::default();
        let result = config.apply_setting("model", "gpt-4").unwrap();
        assert!(result.contains("gpt-4"));
        assert_eq!(config.llm.model, "gpt-4");
    }

    #[test]
    fn setter_opt_string_empty_becomes_none() {
        let mut config = Config::default();
        config.apply_setting("user.name", "alice").unwrap();
        assert_eq!(config.user.name.as_deref(), Some("alice"));
        config.apply_setting("user.name", "").unwrap();
        assert_eq!(config.user.name, None);
    }

    #[test]
    fn setter_parsed_bool() {
        let mut config = Config::default();
        config.apply_setting("sandbox.enabled", "false").unwrap();
        assert!(!config.sandbox.enabled);
        config.apply_setting("sandbox.enabled", "true").unwrap();
        assert!(config.sandbox.enabled);
    }

    #[test]
    fn setter_parsed_invalid_rejects() {
        let mut config = Config::default();
        assert!(config.apply_setting("sandbox.enabled", "maybe").is_err());
    }

    #[test]
    fn setter_nonzero_rejects_zero() {
        let mut config = Config::default();
        assert!(config.apply_setting("max_tokens", "0").is_err());
    }

    #[test]
    fn setter_range_rejects_out_of_bounds() {
        let mut config = Config::default();
        assert!(config.apply_setting("temperature", "5.0").is_err());
        assert!(config.apply_setting("temperature", "-1.0").is_err());
        config.apply_setting("temperature", "1.5").unwrap();
        assert!((config.llm.temperature - 1.5).abs() < f32::EPSILON);
    }

    #[test]
    fn setter_json_invalid_rejects() {
        let mut config = Config::default();
        assert!(config
            .apply_setting("security.blocked_paths", "not json")
            .is_err());
    }

    #[test]
    fn setter_json_count_works() {
        let mut config = Config::default();
        let result = config
            .apply_setting("gateway.bindings", r#"[{"channel":"telegram"}]"#)
            .unwrap();
        assert!(result.contains("1 bindings"));
    }

    #[test]
    fn setter_json_set_works() {
        let mut config = Config::default();
        let result = config
            .apply_setting("security.action_limits", r#"{"shell":10}"#)
            .unwrap();
        assert!(result.contains("(set)"));
    }

    #[test]
    fn setter_json_quoted_works() {
        let mut config = Config::default();
        config.apply_setting("llm.thinking", "high").unwrap();
        assert!(config.llm.thinking.is_enabled());
    }

    #[test]
    fn custom_setter_sandbox_mode_validates() {
        let mut config = Config::default();
        config.apply_setting("sandbox.mode", "strict").unwrap();
        assert_eq!(config.sandbox.mode, "strict");
        assert!(config.apply_setting("sandbox.mode", "chaos").is_err());
    }

    #[test]
    fn custom_setter_workflow_enabled_validates() {
        let mut config = Config::default();
        config.apply_setting("workflow.enabled", "on").unwrap();
        assert_eq!(config.workflow.enabled, "on");
        assert!(config.apply_setting("workflow.enabled", "maybe").is_err());
    }

    #[test]
    fn custom_setter_tts_format_validates() {
        let mut config = Config::default();
        config.apply_setting("tts.default_format", "opus").unwrap();
        assert_eq!(config.tts.default_format, "opus");
        assert!(config.apply_setting("tts.default_format", "mp5").is_err());
    }

    #[test]
    fn custom_setter_collaboration_mode() {
        let mut config = Config::default();
        config
            .apply_setting("conversation.collaboration_mode", "execute")
            .unwrap();
        assert_eq!(
            format!("{}", config.conversation.collaboration_mode),
            "execute"
        );
    }

    #[test]
    fn custom_setter_memory_extra_paths() {
        let mut config = Config::default();
        config
            .apply_setting("memory.extra_paths", "/a, /b, /c")
            .unwrap();
        assert_eq!(config.memory.extra_paths, vec!["/a", "/b", "/c"]);
    }

    #[test]
    fn dynamic_skill_entry_setting() {
        let mut config = Config::default();
        config
            .apply_setting("skills.entries.git.enabled", "false")
            .unwrap();
        assert!(!config.skills.entries["git"].enabled);
    }

    #[test]
    fn unknown_setting_rejects() {
        let mut config = Config::default();
        assert!(config.apply_setting("nonexistent.key", "value").is_err());
    }

    #[test]
    fn registry_count_guard() {
        // Guard against accidentally dropping entries during macro migration.
        // Update this count when adding/removing settings.
        assert!(
            ALL_SETTING_KEYS.len() >= 100,
            "SETTING_REGISTRY should have at least 100 entries, got {}",
            ALL_SETTING_KEYS.len()
        );
    }

    #[test]
    fn every_registry_key_has_working_extractor() {
        let config = Config::default();
        for &(_key, extractor) in SETTING_REGISTRY.iter() {
            // Should not panic
            let _value = extractor(&config);
        }
    }
}
